server:
  port: 8080
zuul:
  routes:
    user-service:
      path: /user-service/**
      url: http://localhost:8081
      stripPrefix: true
    product-service:
      path: /product-service/**
      url: http://localhost:8082
      stripPrefix: true